export type SystemRole =
  | 'SUPER_ADMIN'
  | 'TENANT_ADMIN'
  | 'ORGANIZER'
  | 'TEACHER'
  | 'CREDENTIAL_APPROVER'
  | 'FACILITATOR'
  | 'AUDIT_REVIEWER'
  | 'VIEWER'
  | 'PARTICIPANT';

export type PermissionCode =
  | 'tenant:create'
  | 'tenant:read'
  | 'tenant:update'
  | 'tenant:suspend'
  | 'tenant:reactivate'
  | 'user:create'
  | 'user:read'
  | 'user:update'
  | 'user:delete'
  | 'user:assign_role'
  | 'event:create'
  | 'event:read'
  | 'event:update'
  | 'event:publish'
  | 'event:close'
  | 'enrollment:create'
  | 'enrollment:read'
  | 'attendance:record'
  | 'evaluation:record'
  | 'payment:confirm'
  | 'issuance:approve'
  | 'issuance:reject'
  | 'issuance:read'
  | 'credential:read'
  | 'audit:read'
  | 'audit:export';
